### ISSUE TITLE
not working while using this in my project 

### ISSUE THREAD

**Issue by rvuyyuru2** [kiyasov/platform-hono#1]

**Comment by kiyasov** [comment]
Hi! Can you tell me more?

**Comment by rvuyyuru2** [comment]
i added to fresh app getting errors like deps missing for apollo

**Comment by kiyasov** [comment]
You can set dependencies that are missing. My application already has graphql installed. 
https://github.com/kiyasov/platform-hono/blob/68c53f6be488d0dc03d7a7667b115537ac76e493/package.json#L26

**Comment by rvuyyuru2** [comment]
> You can set dependencies that are missing. My application already has graphql installed.
> 
> https://github.com/kiyasov/platform-hono/blob/68c53f6be488d0dc03d7a7667b115537ac76e493/package.json#L26

why don't to wan't graphql

**Comment by kiyasov** [comment]
You can do fork and use only the adapter
