### ISSUE TITLE
RPC capable?

### ISSUE THREAD

**Issue by Rykuno** [kiyasov/platform-hono#2]
Hono is capable of having an RPC which we have found insanely convenient and handy. I'm not familiar with how http libs integrate into the nest adapter, but is there any way for us to achieve RPC functionality with this lib? 

https://hono.dev/docs/guides/rpc#client

**Comment by kiyasov** [comment]
I haven't had any experience with RPC. I'm afraid I can't help you with that. Maybe someone would like to set up a PR
