### ISSUE TITLE
Exception handler does not work

### ISSUE THREAD

**Issue by 95gabor** [kiyasov/platform-hono#4]
Hi!

I tried to use the exception handler from the README, but not worked for me.

I had to create a new Response object, because the previous error instance had JSON parse error (I only throw a simple new Error() instance in my controller). Here is my solution:

```ts
import { HonoRequest } from '@kiyasov/platform-hono';
import {
  ExceptionFilter,
  Catch,
  ArgumentsHost,
  HttpException,
  InternalServerErrorException,
} from '@nestjs/common';
import { Context } from 'hono';

@Catch()
export class AllExceptionFilter implements ExceptionFilter {
  catch(exception: HttpException, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse<Context>();
    const request = ctx.getRequest<HonoRequest>();

    const status =
      exception.getStatus?.() || new InternalServerErrorException().getStatus();

    response.res = Response.json(
      {
        statusCode: status,
        timestamp: new Date().toISOString(),
        path: request.url,
      },
      { status },
    );
  }
}
```

**Comment by kiyasov** [comment]
Hi! 
Did you enable it via useGlobalFilters?
https://github.com/kiyasov/platform-hono/blob/dba04ff2e8f11e082f758d6a42e3035a9f6818d2/example/src/main.ts#L26

**Comment by 95gabor** [comment]
> Hi! Did you enable it via useGlobalFilters?
> 
> https://github.com/kiyasov/platform-hono/blob/dba04ff2e8f11e082f758d6a42e3035a9f6818d2/example/src/main.ts#L26

Yes, but unfortunately it did not work.

**Comment by kiyasov** [comment]
Can you share the exmaple code at https://replit.com ?

**Comment by 95gabor** [comment]
> Can you share the exmaple code at https://replit.com ?

Sorry, it seems to work here, so something wrong in my environment.

Here is the working example: https://replit.com/@95gabor/platform-hono
